### ISSUE TITLE
Wk14 Lecture summary / notes / slides [Alex]

### ISSUE THREAD

**Issue by ppannuto** [c4cs/c4cs.github.io#214]
I added the videos for each lecture to the homepage, however https://piazza.com/class/ij1jghks3dr59n?cid=479 has a decent request. When you get a chance, could you post your outlines and/or slides to the homepage as well?

Thanks!

**Comment by the-alex** [comment]
Done. I actually didn't see this issue until after I posted the link to my repo. The slides are in the project. You run in as a web server and the slides are served on index.html

56643de
