### ISSUE TITLE
create a reference page for 'dd'

### ISSUE THREAD

**Issue by TBartl** [c4cs/c4cs.github.io#262]
I've used this command in the past for cloning flash drives to ensure they hold exactly the same data and am interested in seeing what else this command can do.

**Comment by ppannuto** [comment]
A heads up for you (and please include a similar warning in your docs), `dd`'s a useful command, but it's also pretty dangerous. It is a very low-level command that writes bytes directly to disks. It doesn't sanity check your arguments, and won't stop you from overwriting critical stuff. Be careful playing around with it, you can easily mess up your (virtual) machine [one of the reasons VMs are great!].

**Comment by mterwill** [comment]
Closed by https://github.com/c4cs/c4cs.github.io/pull/268.
