### ISSUE TITLE
Winter semester HW says F'16 still :D

### ISSUE THREAD

**Issue by ppannuto** [c4cs/c4cs.github.io#276]
![screen shot 2017-01-06 at 20 19 07](https://cloud.githubusercontent.com/assets/339422/21738037/75748022-d44d-11e6-98e0-29ef2765aef0.png)

You also need to run `pdflatex` a few times to get the page numbers to work :P 
[Check out `latexmk` which will automagically run latex enough times for you]

**Comment by mterwill** [comment]
Resolved by 1f550851c9c505a51330825c788e7812afdbc293.
