### ISSUE TITLE
add docs for `ed`

### ISSUE THREAD

**Issue by the-alex** [c4cs/c4cs.github.io#282]
Command was mentioned in lecture but is not defined on our website.

**Comment by afwilkin** [comment]
yea I'll work on that if no one else is

**Comment by mterwill** [comment]
#320 makes me think we ditched this? I haven't been attending lecture this term.

**Comment by the-alex** [comment]
We definitely covered it in lecture this semester, though. I added it because Travis was yelling about a 404 because the `ed` command was listed in the syllabus and it was trying to point to a c4cs/reference page. I added an `ed` template page for this.

**Comment by the-alex** [comment]
Though, as I scroll through, I see I forgot to change the title in the markdown itself so there are a few default "COMMAND" titles in the reference page. I'll fix that now.
