### ISSUE TITLE
/reference page links to last year's advanced hw assignment

### ISSUE THREAD

**Issue by christyliu** [c4cs/c4cs.github.io#284]
A quick fix, but I figured I'd post this as an issue for the sake of bookkeeping 👍

**Comment by the-alex** [comment]
Thanks for pointing this out -- we really appreciate it.

**Comment by the-alex** [comment]
Fixed with 7708e7e. I forgot to include the `#` on the issue number, so I couldn't close the issue from the command line like all the cool kids do.
