### ISSUE TITLE
Create a reference page for ffmpeg

### ISSUE THREAD

**Issue by the-alex** [c4cs/c4cs.github.io#294]
[`ffmpeg`](https://ffmpeg.org/) has come in handy for me more than a few times. It is a program for editing media files. Among other things, it allows you to create `.gifs` from videos, strip just the audio or frames, and convert from one file to another with granularity I haven't seen from any other tool like this. Could be a nice addition. There's definitely stuff I haven't tried yet, either.

**Comment by RemingtonReackhof** [comment]
Claiming this!
