### ISSUE TITLE
Creating reference page for [ifconfig, ip]

### ISSUE THREAD

**Issue by zhecht** [c4cs/c4cs.github.io#299]
Didn't see too many networking commands so requesting to add ifconfig.

**Comment by ppannuto** [comment]
ifconfig is deprecated (though it's not likely to disappear any time soon).
Still, might be better to document it's replacement [maybe a stub page for
ifconfig that explains that it's deprecated and translations from common
ifconfig to new ip commands could be awesome!]

**Comment by ppannuto** [comment]
some more info
http://serverfault.com/questions/458628/should-i-quit-using-ifconfig

**Comment by zhecht** [comment]
wow, TIL ifconfig is a depreciated version of /bin/ip and that /bin/ip is a command haha. Interested in learning the documentation for /bin/ip and willing to create a small stub of ifconfig with a warning that it is depreciated

**Comment by mterwill** [comment]
TIL as well! `ip` isn't included in macOS; always just assumed it was a platform-specific thing.

**Comment by ppannuto** [comment]
Ah.. but as always, brew to the rescue :)

http://superuser.com/questions/687310/ip-command-in-mac-os-x-terminal
