### ISSUE TITLE
Create reference for hash

### ISSUE THREAD

**Issue by sgurnoor** [c4cs/c4cs.github.io#305]
Creating a reference for hash command that displays a hash table of recently executed programs.

**Comment by ppannuto** [comment]
One useful trick to add to this one is using hash to determine if a program
is installed.

It's generally hard to figure out if something is installed without trying
to _run_ that program. You would have to scan the PATH manually or find
something benign like `arm-none-eabi-gcc --version` that would fail if the
application isn't there and not do anything destructive if it is. But then
it's app-specific and kinda annoying. However, you can use hash to test for
existence of a program w/out the side effects of running it, i.e. `hash
arm-none-eabi-gcc && echo got it || echo dont got it`
