### ISSUE TITLE
Should remove the "remember ed" bits from Unix II HW

### ISSUE THREAD

**Issue by ppannuto** [c4cs/c4cs.github.io#320]
We dropped the `ed` stuff for good reason. I think it's confusing to bring it up here.

**Comment by the-alex** [comment]
I dunno -- I don't see the harm in leaving it in. I feel like it's a fun bit of trivia, and we have a healthy amount of that in our homework. I'd just change the phrasing to lose the assumption that we covered it in lecture.

**Comment by ppannuto** [comment]
sgtm
