### ISSUE TITLE
Extra whitespace on short reference pages

### ISSUE THREAD

**Issue by the-alex** [c4cs/c4cs.github.io#329]
Examples: [mv](https://c4cs.github.io/commands/mv), [dot (.)](https://c4cs.github.io/commands/dot)

There's some whitespace buffering at the bottom of these pages (and others). It doesn't really ruin anything, but it's certainly not intentional.

**Comment by mterwill** [comment]
I noticed this when combing through css for #298. Believe [this](https://github.com/c4cs/c4cs.github.io/blob/master/static/css/navbar-fixed-top.css#L2) is the culprit. @ppannuto particular any reason that's there?

**Comment by ppannuto** [comment]
whoa.. that line comes from the initial commit... 

I *think* it had to do with the footer implementation. Once up a time the site had a sticky footer, which does silly looking things if the page height is less than the window size. There's no longer a sticky footer, so probably safe to delete.
