### ISSUE TITLE
diff

### ISSUE THREAD

**Issue by ESattler** [c4cs/c4cs.github.io#72]
Claiming diff command

**Comment by mterwill** [comment]
@ESattler are you still doing `diff`? We're trying to only hold claims for a week.

**Comment by rositawong** [comment]
If he's not doing it I am down to do it! I didn't realize commands are to be claimed. I wrote down some stuff for diff. But if he still has it I can do something else

**Comment by mterwill** [comment]
@rositawong all yours if you want it. @ESattler closing since we didn't hear from you.
